#!/bin/bash
PURPLE=$(tput setaf 99)
ORANGE=$(tput setaf 208)
CLR=$(tput sgr0)
mv .Room1 Room1
mv .Room2 Room2
mv .Room3 Room3
mv .statue statue
echo "A grand room stands before you. A large ${PURPLE}Statue ${CLR}sits against the back of the room beside a sealed entrance. The room has 3 open doorways for each of the other walls."         