#!/bin/bash
RED=$(tput setaf 124)
ORANGE=$(tput setaf 208)
CLR=$(tput sgr0)

#cat .imeCan
echo "${RED}Imetsy${CLR}, another son of Horus, is associated with the South cardinal direction. This statue looks like he could use a drink. Man, if I were down here for who knows how long I'd need one too."