#!/bin/bash
currPath=$(pwd)
echo $currPath
clear

chmod u+x ${currPath}/TombEntrance/lookAround
chmod u+x ${currPath}/TombEntrance/Heiroglyph





YELLOW=$(tput setaf 190)
CLR=$(tput sgr0)


cat .title
#https://patorjk.com/software/taag/#p=testall&v=0&f=Epic&t=Temple%20Of%20Osiris
#maybe some pyramid ascii art here

select option in Play Readme Quit; do
	case $option in
		"Play")
  
    











    #mv .Tomb Tomb
			break
		;;
		"Readme")
			cat Readme
		;;
		"Quit")
			exit
		;;
		*)
		;;
	esac
done

echo -e "What is your last name?"
read NAME
echo "Hello, Professor $NAME!"
echo "You are the world's leading ${YELLOW}egyptologist${CLR}"
echo "Right now represents the defining moment of your career!"
echo "You have found the ${YELLOW}Temple of Osiris${CLR}"

#OBJECT STATS
export OBJ1STAT
export OBJ2STAT
export OBJ3STAT
OBJ1STAT=0
OBJ2STAT=0
OBJ3STAT=0
#https://patorjk.com/software/taag/#p=display&f=Hieroglyphs&t=