#!/bin/bash

: << 'HIEROGLYPH'

  _              ,-.       ,-.,-==.            
 `-)            <,- \_____/  ` (  (\           
 _/,' .-===-.,    /  ___. \     |\.\\          
(___) `.___.'  ,_(__/ ,_(__\   _]_]`\\ ^^^^^^^ 

HIEROGLYPH

#USE YOUR TRANSLATOR TO UNVEIL THESE GLYPHS BY DELETING THE # ON THE NEXT LINE
#CHANGE TO INSERT MODE WITH I
#CONFIRM WITH ESC KEY, 'wq!", ENTER KEY
mv .translatedglyph1 translatedglyph1

#USE cat TO READ TRANSLATED GLYPHS
