#!/bin/bash
PURPLE=$(tput setaf 99)
RED=$(tput setaf 124)
ORANGE=$(tput setaf 208)
CLR=$(tput sgr0)

echo "

You are four sided room with three of walls covered in hieroglyphs. In the middle of the wall furthest from you, there is a ${ORANGE}lever${CLR} and a blocked ${ORANGE}door${CLR}.

"
mv .hieroglyph1 hieroglyph1
mv .hieroglyph2 hieroglyph2
mv .hieroglyph3 hieroglyph3

mv .confirmLever confirmLever
