#!/bin/bash
PURPLE=$(tput setaf 99)
ORANGE=$(tput setaf 208)
CLR=$(tput sgr0)

echo "A grand room stands before you. A large ${PURPLE}Statue ${CLR}sits against the back of the room beside a sealed entrance. The tomb floor seems to be littered with various ${ORANGE}objects${CLR}."