#!/bin/bash
PURPLE=$(tput setaf 99)
ORANGE=$(tput setaf 208)
CLR=$(tput sgr0)

echo "It's a small room with little inside. There seems to be a sign posted to one of the walls."

mv .Object1 Object1
mv .Sign Sign