#!/bin/bash
RED=$(tput setaf 124)
ORANGE=$(tput setaf 208)
CLR=$(tput sgr0)

echo "

As you approach the busts you recognize the figures. The gods are the four sons of Horus-- ${RED}Imetsy${CLR}, ${RED}Duamutef${CLR}, ${RED}Hapi${CLR}, and ${RED}Qebehsenuef${CLR} respectively. They are intended to protect specific organs of the deceased, yet their ${ORANGE}canopic jars${CLR} seem to be missing...

"