#!/bin/bash
echo "Within these walls is the phrase to safely pass"
echo "Enter phrase?"
select option in Yes No;  do
case $option in

"Yes"|"yes")
 read -p "Enter the phrase
" phrase
  if [ "$phrase" = 'Suffering in search of truth gives true meaning to the truth' ]; then
    echo "Your words speak great truths. You may carry on."\
    echo "Tomb of Osiris has been opened."
mv .TombOfOsiris TombOfOsiris
    else
  echo "Is this a joke to you? Try again."
fi
break
    ;;

"No"|"no")
  echo "Use Ctrl+D to exit"
    ;;

 

  *)
   echo ""
    ;;
esac
done